### ISSUE TITLE
Broken package error refuses nix-shell launch 

### ISSUE THREAD

**Issue by pixln** [turion/essence-of-live-coding-tutorial#2]
While launching `nix-shell`, I receive the following error:

```
essence-of-live-coding-tutorial git:(master) nix-shell
..
error: Package ‘essence-of-live-coding-0.1.0.3’ in /nix/store/smvbabpccmq4xmk7c6r2jnhsxf73rbbh-nixpkgs-20.09pre237891.f9eba87bf03/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:83143 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

Shall I follow one of the mentioned instructions?

**Comment by turion** [comment]
@pixln I have a better option: Can you do `git pull` and try to launch `nix-shell` again?

**Comment by turion** [comment]
## Background

NixOS still thinks that these packages are broken although they are fixed since quite some time, afaikt. But that doesn't matter so much because that version is outdated anyways. I supplied the up-to-date versions in the nix shell now, so updating this repo should be fine.
